version: 1
formatters:
  simple:
    format: '[%(asctime)s] [%(levelname)s] [%(threadName)s] [%(pathname)s] [%(module)s:%(lineno)d] %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
handlers:
  file:
    class: logging.FileHandler
    level: DEBUG
    formatter: simple
    filename: /tmp/resLogAnalyse.log
loggers:
  simpleExample:
    level: DEBUG
    handlers: [file]
    propagate: yes
